#
# Makefile
# yqiu, 2016-10-27 18:33
#

all:
	# ocamlfind ocamlopt -package lwt,lwt.unix -linkpkg -o counter-server ./counter-server.ml
	ocamlbuild -use-ocamlfind -pkgs lwt,lwt.unix server.byte client.byte



# vim:ft=make
#
