#
# Makefile
# yqiu, 2016-09-28 00:07
#

peek:
	lualatex *.tex && rm -f *.aux *.log *.out *.toc && evince *.pdf

all:
	lualatex *.tex && rm -f *.aux *.log *.out *.toc

# clean:
# 	rm -f *.pdf *.aux *.log *.out *.toc

# filter:
# 	rm -f *.aux *.log *.out *.toc


# vim:ft=make
#
